/*
 * This file is part of Conjugator.
 *
 * Conjugator is free software:
 * you can redistribute it and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation,
 * either version 3 of the License,
 * or (at your option) any later version.
 * Conjugator is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with Conjugator.
 * If not, see <https://www.gnu.org/licenses/>.
 */

val localVerbConjugations =
"""
{
   "abejoti":[
      {
         "verb":{
            "infinitive":"abejoti",
            "present":"abejoja",
            "past":"abejojo"
         },
         "tense":"Present",
         "forms":[
            "abejoju",
            "abejoji",
            "abejoja",
            "abejojame",
            "abejojate",
            "abejoja"
         ]
      },
      {
         "verb":{
            "infinitive":"abejoti",
            "present":"abejoja",
            "past":"abejojo"
         },
         "tense":"Past",
         "forms":[
            "abejojau",
            "abejojai",
            "abejojo",
            "abejojome",
            "abejojote",
            "abejojo"
         ]
      },
      {
         "verb":{
            "infinitive":"abejoti",
            "present":"abejoja",
            "past":"abejojo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "abejodavau",
            "abejodavai",
            "abejodavo",
            "abejodavome",
            "abejodavote",
            "abejodavo"
         ]
      },
      {
         "verb":{
            "infinitive":"abejoti",
            "present":"abejoja",
            "past":"abejojo"
         },
         "tense":"Future",
         "forms":[
            "abejosiu",
            "abejosi",
            "abejos",
            "abejosime",
            "abejosite",
            "abejos"
         ]
      },
      {
         "verb":{
            "infinitive":"abejoti",
            "present":"abejoja",
            "past":"abejojo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "abejok",
            "tegu abejoja",
            "abejokime",
            "abejokite",
            "tegu abejoja"
         ]
      },
      {
         "verb":{
            "infinitive":"abejoti",
            "present":"abejoja",
            "past":"abejojo"
         },
         "tense":"Conditional",
         "forms":[
            "abejočiau",
            "abejotum",
            "abejotų",
            "abejotume / abejotumėme",
            "abejotute / abejotumėte",
            "abejotų"
         ]
      }
   ],
   "aiškinti":[
      {
         "verb":{
            "infinitive":"aiškinti",
            "present":"aiškina",
            "past":"aiškino"
         },
         "tense":"Present",
         "forms":[
            "aiškinu",
            "aiškini",
            "aiškina",
            "aiškiname",
            "aiškinate",
            "aiškina"
         ]
      },
      {
         "verb":{
            "infinitive":"aiškinti",
            "present":"aiškina",
            "past":"aiškino"
         },
         "tense":"Past",
         "forms":[
            "aiškinau",
            "aiškinai",
            "aiškino",
            "aiškinome",
            "aiškinote",
            "aiškino"
         ]
      },
      {
         "verb":{
            "infinitive":"aiškinti",
            "present":"aiškina",
            "past":"aiškino"
         },
         "tense":"PastContiniuos",
         "forms":[
            "aiškindavau",
            "aiškindavai",
            "aiškindavo",
            "aiškindavome",
            "aiškindavote",
            "aiškindavo"
         ]
      },
      {
         "verb":{
            "infinitive":"aiškinti",
            "present":"aiškina",
            "past":"aiškino"
         },
         "tense":"Future",
         "forms":[
            "aiškinsiu",
            "aiškinsi",
            "aiškins",
            "aiškinsime",
            "aiškinsite",
            "aiškins"
         ]
      },
      {
         "verb":{
            "infinitive":"aiškinti",
            "present":"aiškina",
            "past":"aiškino"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "aiškink",
            "tegu aiškina",
            "aiškinkime",
            "aiškinkite",
            "tegu aiškina"
         ]
      },
      {
         "verb":{
            "infinitive":"aiškinti",
            "present":"aiškina",
            "past":"aiškino"
         },
         "tense":"Conditional",
         "forms":[
            "aiškinčiau",
            "aiškintum",
            "aiškintų",
            "aiškintume / aiškintumėme",
            "aiškintute / aiškintumėte",
            "aiškintų"
         ]
      }
   ],
   "apsistoti":[
      {
         "verb":{
            "infinitive":"apsistoti",
            "present":"apsistoja",
            "past":"apsistojo"
         },
         "tense":"Present",
         "forms":[
            "apsistoju",
            "apsistoji",
            "apsistoja",
            "apsistojame",
            "apsistojate",
            "apsistoja"
         ]
      },
      {
         "verb":{
            "infinitive":"apsistoti",
            "present":"apsistoja",
            "past":"apsistojo"
         },
         "tense":"Past",
         "forms":[
            "apsistojau",
            "apsistojai",
            "apsistojo",
            "apsistojome",
            "apsistojote",
            "apsistojo"
         ]
      },
      {
         "verb":{
            "infinitive":"apsistoti",
            "present":"apsistoja",
            "past":"apsistojo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "apsistodavau",
            "apsistodavai",
            "apsistodavo",
            "apsistodavome",
            "apsistodavote",
            "apsistodavo"
         ]
      },
      {
         "verb":{
            "infinitive":"apsistoti",
            "present":"apsistoja",
            "past":"apsistojo"
         },
         "tense":"Future",
         "forms":[
            "apsistosiu",
            "apsistosi",
            "apsistos",
            "apsistosime",
            "apsistosite",
            "apsistos"
         ]
      },
      {
         "verb":{
            "infinitive":"apsistoti",
            "present":"apsistoja",
            "past":"apsistojo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "apsistok",
            "tegu apsistoja",
            "apsistokime",
            "apsistokite",
            "tegu apsistoja"
         ]
      },
      {
         "verb":{
            "infinitive":"apsistoti",
            "present":"apsistoja",
            "past":"apsistojo"
         },
         "tense":"Conditional",
         "forms":[
            "apsistočiau",
            "apsistotum",
            "apsistotų",
            "apsistotume / apsistotumėme",
            "apsistotute / apsistotumėte",
            "apsistotų"
         ]
      }
   ],
   "atleisti":[
      {
         "verb":{
            "infinitive":"atleisti",
            "present":"atleidžia",
            "past":"atleido"
         },
         "tense":"Present",
         "forms":[
            "atleidžiu",
            "atleidži",
            "atleidžia",
            "atleidžiame",
            "atleidžiate",
            "atleidžia"
         ]
      },
      {
         "verb":{
            "infinitive":"atleisti",
            "present":"atleidžia",
            "past":"atleido"
         },
         "tense":"Past",
         "forms":[
            "atleidau",
            "atleidai",
            "atleido",
            "atleidome",
            "atleidote",
            "atleido"
         ]
      },
      {
         "verb":{
            "infinitive":"atleisti",
            "present":"atleidžia",
            "past":"atleido"
         },
         "tense":"PastContiniuos",
         "forms":[
            "atleisdavau",
            "atleisdavai",
            "atleisdavo",
            "atleisdavome",
            "atleisdavote",
            "atleisdavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atleisti",
            "present":"atleidžia",
            "past":"atleido"
         },
         "tense":"Future",
         "forms":[
            "atleisiu",
            "atleisi",
            "atleis",
            "atleisime",
            "atleisite",
            "atleis"
         ]
      },
      {
         "verb":{
            "infinitive":"atleisti",
            "present":"atleidžia",
            "past":"atleido"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "atleisk",
            "tegu atleidžia",
            "atleiskime",
            "atleiskite",
            "tegu atleidžia"
         ]
      },
      {
         "verb":{
            "infinitive":"atleisti",
            "present":"atleidžia",
            "past":"atleido"
         },
         "tense":"Conditional",
         "forms":[
            "atleisčiau",
            "atleistum",
            "atleistų",
            "atleistume / atleistumėme",
            "atleistute / atleistumėte",
            "atleistų"
         ]
      }
   ],
   "atostogauti":[
      {
         "verb":{
            "infinitive":"atostogauti",
            "present":"atostogauja",
            "past":"atostogavo"
         },
         "tense":"Present",
         "forms":[
            "atostogauju",
            "atostogauji",
            "atostogauja",
            "atostogaujame",
            "atostogaujate",
            "atostogauja"
         ]
      },
      {
         "verb":{
            "infinitive":"atostogauti",
            "present":"atostogauja",
            "past":"atostogavo"
         },
         "tense":"Past",
         "forms":[
            "atostogavau",
            "atostogavai",
            "atostogavo",
            "atostogavome",
            "atostogavote",
            "atostogavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atostogauti",
            "present":"atostogauja",
            "past":"atostogavo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "atostogaudavau",
            "atostogaudavai",
            "atostogaudavo",
            "atostogaudavome",
            "atostogaudavote",
            "atostogaudavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atostogauti",
            "present":"atostogauja",
            "past":"atostogavo"
         },
         "tense":"Future",
         "forms":[
            "atostogausiu",
            "atostogausi",
            "atostogaus",
            "atostogausime",
            "atostogausite",
            "atostogaus"
         ]
      },
      {
         "verb":{
            "infinitive":"atostogauti",
            "present":"atostogauja",
            "past":"atostogavo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "atostogauk",
            "tegu atostogauja",
            "atostogaukime",
            "atostogaukite",
            "tegu atostogauja"
         ]
      },
      {
         "verb":{
            "infinitive":"atostogauti",
            "present":"atostogauja",
            "past":"atostogavo"
         },
         "tense":"Conditional",
         "forms":[
            "atostogaučiau",
            "atostogautum",
            "atostogautų",
            "atostogautume / atostogautumėme",
            "atostogautute / atostogautumėte",
            "atostogautų"
         ]
      }
   ],
   "atrodyti":[
      {
         "verb":{
            "infinitive":"atrodyti",
            "present":"atrodo",
            "past":"atrodė"
         },
         "tense":"Present",
         "forms":[
            "atrodau",
            "atrodai",
            "atrodo",
            "atrodome",
            "atrodote",
            "atrodo"
         ]
      },
      {
         "verb":{
            "infinitive":"atrodyti",
            "present":"atrodo",
            "past":"atrodė"
         },
         "tense":"Past",
         "forms":[
            "atrodžiau",
            "atrodei",
            "atrodė",
            "atrodėme",
            "atrodėte",
            "atrodė"
         ]
      },
      {
         "verb":{
            "infinitive":"atrodyti",
            "present":"atrodo",
            "past":"atrodė"
         },
         "tense":"PastContiniuos",
         "forms":[
            "atrodydavau",
            "atrodydavai",
            "atrodydavo",
            "atrodydavome",
            "atrodydavote",
            "atrodydavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atrodyti",
            "present":"atrodo",
            "past":"atrodė"
         },
         "tense":"Future",
         "forms":[
            "atrodysiu",
            "atrodysi",
            "atrodys",
            "atrodysime",
            "atrodysite",
            "atrodys"
         ]
      },
      {
         "verb":{
            "infinitive":"atrodyti",
            "present":"atrodo",
            "past":"atrodė"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "atrodyk",
            "tegu atrodo",
            "atrodykime",
            "atrodykite",
            "tegu atrodo"
         ]
      },
      {
         "verb":{
            "infinitive":"atrodyti",
            "present":"atrodo",
            "past":"atrodė"
         },
         "tense":"Conditional",
         "forms":[
            "atrodyčiau",
            "atrodytum",
            "atrodytų",
            "atrodytume / atrodytumėme",
            "atrodytute / atrodytumėte",
            "atrodytų"
         ]
      }
   ],
   "atsakyti":[
      {
         "verb":{
            "infinitive":"atsakyti",
            "present":"atsako",
            "past":"atsakė"
         },
         "tense":"Present",
         "forms":[
            "atsakau",
            "atsakai",
            "atsako",
            "atsakome",
            "atsakote",
            "atsako"
         ]
      },
      {
         "verb":{
            "infinitive":"atsakyti",
            "present":"atsako",
            "past":"atsakė"
         },
         "tense":"Past",
         "forms":[
            "atsakiau",
            "atsakei",
            "atsakė",
            "atsakėme",
            "atsakėte",
            "atsakė"
         ]
      },
      {
         "verb":{
            "infinitive":"atsakyti",
            "present":"atsako",
            "past":"atsakė"
         },
         "tense":"PastContiniuos",
         "forms":[
            "atsakydavau",
            "atsakydavai",
            "atsakydavo",
            "atsakydavome",
            "atsakydavote",
            "atsakydavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atsakyti",
            "present":"atsako",
            "past":"atsakė"
         },
         "tense":"Future",
         "forms":[
            "atsakysiu",
            "atsakysi",
            "atsakys",
            "atsakysime",
            "atsakysite",
            "atsakys"
         ]
      },
      {
         "verb":{
            "infinitive":"atsakyti",
            "present":"atsako",
            "past":"atsakė"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "atsakyk",
            "tegu atsako",
            "atsakykime",
            "atsakykite",
            "tegu atsako"
         ]
      },
      {
         "verb":{
            "infinitive":"atsakyti",
            "present":"atsako",
            "past":"atsakė"
         },
         "tense":"Conditional",
         "forms":[
            "atsakyčiau",
            "atsakytum",
            "atsakytų",
            "atsakytume / atsakytumėme",
            "atsakytute / atsakytumėte",
            "atsakytų"
         ]
      }
   ],
   "atsiliepti":[
      {
         "verb":{
            "infinitive":"atsiliepti",
            "present":"atsiliepia",
            "past":"atsiliepė"
         },
         "tense":"Present",
         "forms":[
            "atsiliepiu",
            "atsiliepi",
            "atsiliepia",
            "atsiliepiame",
            "atsiliepiate",
            "atsiliepia"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiliepti",
            "present":"atsiliepia",
            "past":"atsiliepė"
         },
         "tense":"Past",
         "forms":[
            "atsiliepiau",
            "atsiliepei",
            "atsiliepė",
            "atsiliepėme",
            "atsiliepėte",
            "atsiliepė"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiliepti",
            "present":"atsiliepia",
            "past":"atsiliepė"
         },
         "tense":"PastContiniuos",
         "forms":[
            "atsiliepdavau",
            "atsiliepdavai",
            "atsiliepdavo",
            "atsiliepdavome",
            "atsiliepdavote",
            "atsiliepdavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiliepti",
            "present":"atsiliepia",
            "past":"atsiliepė"
         },
         "tense":"Future",
         "forms":[
            "atsiliepsiu",
            "atsiliepsi",
            "atsilieps",
            "atsiliepsime",
            "atsiliepsite",
            "atsilieps"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiliepti",
            "present":"atsiliepia",
            "past":"atsiliepė"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "atsiliepk",
            "tegu atsiliepia",
            "atsiliepkime",
            "atsiliepkite",
            "tegu atsiliepia"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiliepti",
            "present":"atsiliepia",
            "past":"atsiliepė"
         },
         "tense":"Conditional",
         "forms":[
            "atsiliepčiau",
            "atsilieptum",
            "atsilieptų",
            "atsilieptume / atsilieptumėme",
            "atsilieptute / atsilieptumėte",
            "atsilieptų"
         ]
      }
   ],
   "atsiminti":[
      {
         "verb":{
            "infinitive":"atsiminti",
            "present":"atsimena",
            "past":"atsiminė"
         },
         "tense":"Present",
         "forms":[
            "atsimenu",
            "atsimeni",
            "atsimena",
            "atsimename",
            "atsimenate",
            "atsimena"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiminti",
            "present":"atsimena",
            "past":"atsiminė"
         },
         "tense":"Past",
         "forms":[
            "atsiminiau",
            "atsiminei",
            "atsiminė",
            "atsiminėme",
            "atsiminėte",
            "atsiminė"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiminti",
            "present":"atsimena",
            "past":"atsiminė"
         },
         "tense":"PastContiniuos",
         "forms":[
            "atsimindavau",
            "atsimindavai",
            "atsimindavo",
            "atsimindavome",
            "atsimindavote",
            "atsimindavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiminti",
            "present":"atsimena",
            "past":"atsiminė"
         },
         "tense":"Future",
         "forms":[
            "atsiminsiu",
            "atsiminsi",
            "atsimins",
            "atsiminsime",
            "atsiminsite",
            "atsimins"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiminti",
            "present":"atsimena",
            "past":"atsiminė"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "atsimink",
            "tegu atsimena",
            "atsiminkime",
            "atsiminkite",
            "tegu atsimena"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiminti",
            "present":"atsimena",
            "past":"atsiminė"
         },
         "tense":"Conditional",
         "forms":[
            "atsiminčiau",
            "atsimintum",
            "atsimintų",
            "atsimintume / atsimintumėme",
            "atsimintute / atsimintumėte",
            "atsimintų"
         ]
      }
   ],
   "atsiprašyti":[
      {
         "verb":{
            "infinitive":"atsiprašyti",
            "present":"atsiprašo",
            "past":"atsiprašė"
         },
         "tense":"Present",
         "forms":[
            "atsiprašau",
            "atsiprašai",
            "atsiprašo",
            "atsiprašome",
            "atsiprašote",
            "atsiprašo"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiprašyti",
            "present":"atsiprašo",
            "past":"atsiprašė"
         },
         "tense":"Past",
         "forms":[
            "atsiprašiau",
            "atsiprašei",
            "atsiprašė",
            "atsiprašėme",
            "atsiprašėte",
            "atsiprašė"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiprašyti",
            "present":"atsiprašo",
            "past":"atsiprašė"
         },
         "tense":"PastContiniuos",
         "forms":[
            "atsiprašydavau",
            "atsiprašydavai",
            "atsiprašydavo",
            "atsiprašydavome",
            "atsiprašydavote",
            "atsiprašydavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiprašyti",
            "present":"atsiprašo",
            "past":"atsiprašė"
         },
         "tense":"Future",
         "forms":[
            "atsiprašysiu",
            "atsiprašysi",
            "atsiprašys",
            "atsiprašysime",
            "atsiprašysite",
            "atsiprašys"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiprašyti",
            "present":"atsiprašo",
            "past":"atsiprašė"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "atsiprašyk",
            "tegu atsiprašo",
            "atsiprašykime",
            "atsiprašykite",
            "tegu atsiprašo"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiprašyti",
            "present":"atsiprašo",
            "past":"atsiprašė"
         },
         "tense":"Conditional",
         "forms":[
            "atsiprašyčiau",
            "atsiprašytum",
            "atsiprašytų",
            "atsiprašytume / atsiprašytumėme",
            "atsiprašytute / atsiprašytumėte",
            "atsiprašytų"
         ]
      }
   ],
   "atsisakyti":[
      {
         "verb":{
            "infinitive":"atsisakyti",
            "present":"atsisako",
            "past":"atsisakė"
         },
         "tense":"Present",
         "forms":[
            "atsisakau",
            "atsisakai",
            "atsisako",
            "atsisakome",
            "atsisakote",
            "atsisako"
         ]
      },
      {
         "verb":{
            "infinitive":"atsisakyti",
            "present":"atsisako",
            "past":"atsisakė"
         },
         "tense":"Past",
         "forms":[
            "atsisakiau",
            "atsisakei",
            "atsisakė",
            "atsisakėme",
            "atsisakėte",
            "atsisakė"
         ]
      },
      {
         "verb":{
            "infinitive":"atsisakyti",
            "present":"atsisako",
            "past":"atsisakė"
         },
         "tense":"PastContiniuos",
         "forms":[
            "atsisakydavau",
            "atsisakydavai",
            "atsisakydavo",
            "atsisakydavome",
            "atsisakydavote",
            "atsisakydavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atsisakyti",
            "present":"atsisako",
            "past":"atsisakė"
         },
         "tense":"Future",
         "forms":[
            "atsisakysiu",
            "atsisakysi",
            "atsisakys",
            "atsisakysime",
            "atsisakysite",
            "atsisakys"
         ]
      },
      {
         "verb":{
            "infinitive":"atsisakyti",
            "present":"atsisako",
            "past":"atsisakė"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "atsisakyk",
            "tegu atsisako",
            "atsisakykime",
            "atsisakykite",
            "tegu atsisako"
         ]
      },
      {
         "verb":{
            "infinitive":"atsisakyti",
            "present":"atsisako",
            "past":"atsisakė"
         },
         "tense":"Conditional",
         "forms":[
            "atsisakyčiau",
            "atsisakytum",
            "atsisakytų",
            "atsisakytume / atsisakytumėme",
            "atsisakytute / atsisakytumėte",
            "atsisakytų"
         ]
      }
   ],
   "auginti":[
      {
         "verb":{
            "infinitive":"auginti",
            "present":"augina",
            "past":"augino"
         },
         "tense":"Present",
         "forms":[
            "auginu",
            "augini",
            "augina",
            "auginame",
            "auginate",
            "augina"
         ]
      },
      {
         "verb":{
            "infinitive":"auginti",
            "present":"augina",
            "past":"augino"
         },
         "tense":"Past",
         "forms":[
            "auginau",
            "auginai",
            "augino",
            "auginome",
            "auginote",
            "augino"
         ]
      },
      {
         "verb":{
            "infinitive":"auginti",
            "present":"augina",
            "past":"augino"
         },
         "tense":"PastContiniuos",
         "forms":[
            "augindavau",
            "augindavai",
            "augindavo",
            "augindavome",
            "augindavote",
            "augindavo"
         ]
      },
      {
         "verb":{
            "infinitive":"auginti",
            "present":"augina",
            "past":"augino"
         },
         "tense":"Future",
         "forms":[
            "auginsiu",
            "auginsi",
            "augins",
            "auginsime",
            "auginsite",
            "augins"
         ]
      },
      {
         "verb":{
            "infinitive":"auginti",
            "present":"augina",
            "past":"augino"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "augink",
            "tegu augina",
            "auginkime",
            "auginkite",
            "tegu augina"
         ]
      },
      {
         "verb":{
            "infinitive":"auginti",
            "present":"augina",
            "past":"augino"
         },
         "tense":"Conditional",
         "forms":[
            "auginčiau",
            "augintum",
            "augintų",
            "augintume / augintumėme",
            "augintute / augintumėte",
            "augintų"
         ]
      }
   ],
   "augti":[
      {
         "verb":{
            "infinitive":"augti",
            "present":"auga",
            "past":"augo"
         },
         "tense":"Present",
         "forms":[
            "augu",
            "augi",
            "auga",
            "augame",
            "augate",
            "auga"
         ]
      },
      {
         "verb":{
            "infinitive":"augti",
            "present":"auga",
            "past":"augo"
         },
         "tense":"Past",
         "forms":[
            "augau",
            "augai",
            "augo",
            "augome",
            "augote",
            "augo"
         ]
      },
      {
         "verb":{
            "infinitive":"augti",
            "present":"auga",
            "past":"augo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "augdavau",
            "augdavai",
            "augdavo",
            "augdavome",
            "augdavote",
            "augdavo"
         ]
      },
      {
         "verb":{
            "infinitive":"augti",
            "present":"auga",
            "past":"augo"
         },
         "tense":"Future",
         "forms":[
            "augsiu",
            "augsi",
            "augs",
            "augsime",
            "augsite",
            "augs"
         ]
      },
      {
         "verb":{
            "infinitive":"augti",
            "present":"auga",
            "past":"augo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "auk",
            "tegu auga",
            "aukime",
            "aukite",
            "tegu auga"
         ]
      },
      {
         "verb":{
            "infinitive":"augti",
            "present":"auga",
            "past":"augo"
         },
         "tense":"Conditional",
         "forms":[
            "augčiau",
            "augtum",
            "augtų",
            "augtume / augtumėme",
            "augtute / augtumėte",
            "augtų"
         ]
      }
   ],
   "auklėti":[
      {
         "verb":{
            "infinitive":"auklėti",
            "present":"auklėja",
            "past":"auklėjo"
         },
         "tense":"Present",
         "forms":[
            "auklėju",
            "auklėji",
            "auklėja",
            "auklėjame",
            "auklėjate",
            "auklėja"
         ]
      },
      {
         "verb":{
            "infinitive":"auklėti",
            "present":"auklėja",
            "past":"auklėjo"
         },
         "tense":"Past",
         "forms":[
            "auklėjau",
            "auklėjai",
            "auklėjo",
            "auklėjome",
            "auklėjote",
            "auklėjo"
         ]
      },
      {
         "verb":{
            "infinitive":"auklėti",
            "present":"auklėja",
            "past":"auklėjo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "auklėdavau",
            "auklėdavai",
            "auklėdavo",
            "auklėdavome",
            "auklėdavote",
            "auklėdavo"
         ]
      },
      {
         "verb":{
            "infinitive":"auklėti",
            "present":"auklėja",
            "past":"auklėjo"
         },
         "tense":"Future",
         "forms":[
            "auklėsiu",
            "auklėsi",
            "auklės",
            "auklėsime",
            "auklėsite",
            "auklės"
         ]
      },
      {
         "verb":{
            "infinitive":"auklėti",
            "present":"auklėja",
            "past":"auklėjo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "auklėk",
            "tegu auklėja",
            "auklėkime",
            "auklėkite",
            "tegu auklėja"
         ]
      },
      {
         "verb":{
            "infinitive":"auklėti",
            "present":"auklėja",
            "past":"auklėjo"
         },
         "tense":"Conditional",
         "forms":[
            "auklėčiau",
            "auklėtum",
            "auklėtų",
            "auklėtume / auklėtumėme",
            "auklėtute / auklėtumėte",
            "auklėtų"
         ]
      }
   ],
   "autis":[
      {
         "verb":{
            "infinitive":"autis",
            "present":"aunasi",
            "past":"avėsi"
         },
         "tense":"Present",
         "forms":[
            "aunuosi",
            "auniesi",
            "aunasi",
            "aunamės",
            "aunatės",
            "aunasi"
         ]
      },
      {
         "verb":{
            "infinitive":"autis",
            "present":"aunasi",
            "past":"avėsi"
         },
         "tense":"Past",
         "forms":[
            "aviausi",
            "aveisi",
            "avėsi",
            "avėmės",
            "avėtės",
            "avėsi"
         ]
      },
      {
         "verb":{
            "infinitive":"autis",
            "present":"aunasi",
            "past":"avėsi"
         },
         "tense":"PastContiniuos",
         "forms":[
            "audavausi",
            "audavaisi",
            "audavosi",
            "audavomės",
            "audavotės",
            "audavosi"
         ]
      },
      {
         "verb":{
            "infinitive":"autis",
            "present":"aunasi",
            "past":"avėsi"
         },
         "tense":"Future",
         "forms":[
            "ausiuosi",
            "ausiesi",
            "ausis",
            "ausimės",
            "ausitės",
            "ausis"
         ]
      },
      {
         "verb":{
            "infinitive":"autis",
            "present":"aunasi",
            "past":"avėsi"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "aukis",
            "tegu aunasi / tesiauna",
            "aukimės",
            "aukitės",
            "tegu aunasi / tesiauna"
         ]
      },
      {
         "verb":{
            "infinitive":"autis",
            "present":"aunasi",
            "past":"avėsi"
         },
         "tense":"Conditional",
         "forms":[
            "aučiausi",
            "autumeisi",
            "autųsi",
            "autumės / autumėmės",
            "aututės / autumėtės",
            "autųsi"
         ]
      }
   ],
   "baigti":[
      {
         "verb":{
            "infinitive":"baigti",
            "present":"baigia",
            "past":"baigė"
         },
         "tense":"Present",
         "forms":[
            "baigiu",
            "baigi",
            "baigia",
            "baigiame",
            "baigiate",
            "baigia"
         ]
      },
      {
         "verb":{
            "infinitive":"baigti",
            "present":"baigia",
            "past":"baigė"
         },
         "tense":"Past",
         "forms":[
            "baigiau",
            "baigei",
            "baigė",
            "baigėme",
            "baigėte",
            "baigė"
         ]
      },
      {
         "verb":{
            "infinitive":"baigti",
            "present":"baigia",
            "past":"baigė"
         },
         "tense":"PastContiniuos",
         "forms":[
            "baigdavau",
            "baigdavai",
            "baigdavo",
            "baigdavome",
            "baigdavote",
            "baigdavo"
         ]
      },
      {
         "verb":{
            "infinitive":"baigti",
            "present":"baigia",
            "past":"baigė"
         },
         "tense":"Future",
         "forms":[
            "baigsiu",
            "baigsi",
            "baigs",
            "baigsime",
            "baigsite",
            "baigs"
         ]
      },
      {
         "verb":{
            "infinitive":"baigti",
            "present":"baigia",
            "past":"baigė"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "baik",
            "tegu baigia",
            "baikime",
            "baikite",
            "tegu baigia"
         ]
      },
      {
         "verb":{
            "infinitive":"baigti",
            "present":"baigia",
            "past":"baigė"
         },
         "tense":"Conditional",
         "forms":[
            "baigčiau",
            "baigtum",
            "baigtų",
            "baigtume / baigtumėme",
            "baigtute / baigtumėte",
            "baigtų"
         ]
      }
   ],
   "eiti":[
      {
         "verb":{
            "infinitive":"eiti",
            "present":"eina",
            "past":"ėjo"
         },
         "tense":"Present",
         "forms":[
            "einu",
            "eini",
            "eina",
            "einame",
            "einate",
            "eina"
         ]
      },
      {
         "verb":{
            "infinitive":"eiti",
            "present":"eina",
            "past":"ėjo"
         },
         "tense":"Past",
         "forms":[
            "ėjau",
            "ėjai",
            "ėjo",
            "ėjome",
            "ėjote",
            "ėjo"
         ]
      },
      {
         "verb":{
            "infinitive":"eiti",
            "present":"eina",
            "past":"ėjo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "eidavau",
            "eidavai",
            "eidavo",
            "eidavome",
            "eidavote",
            "eidavo"
         ]
      },
      {
         "verb":{
            "infinitive":"eiti",
            "present":"eina",
            "past":"ėjo"
         },
         "tense":"Future",
         "forms":[
            "eisiu",
            "eisi",
            "eis",
            "eisime",
            "eisite",
            "eis"
         ]
      },
      {
         "verb":{
            "infinitive":"eiti",
            "present":"eina",
            "past":"ėjo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "eik",
            "tegu eina",
            "eikime",
            "eikite",
            "tegu eina"
         ]
      },
      {
         "verb":{
            "infinitive":"eiti",
            "present":"eina",
            "past":"ėjo"
         },
         "tense":"Conditional",
         "forms":[
            "eičiau",
            "eitum",
            "eitų",
            "eitume / eitumėme",
            "eitute / eitumėte",
            "eitų"
         ]
      }
   ]
}
"""
