/*
 * This file is part of Conjugator.
 *
 * Conjugator is free software:
 * you can redistribute it and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation,
 * either version 3 of the License,
 * or (at your option) any later version.
 * Conjugator is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with Conjugator.
 * If not, see <https://www.gnu.org/licenses/>.
 */

val localVerbConjugations =
"""
{
   "abejoti":[
      {
         "verb":{
            "infinitive":"abejoti",
            "present":"abejoja",
            "past":"abejojo"
         },
         "tense":"Present",
         "forms":[
            "abejoju",
            "abejoji",
            "abejoja",
            "abejojame",
            "abejojate",
            "abejoja"
         ]
      },
      {
         "verb":{
            "infinitive":"abejoti",
            "present":"abejoja",
            "past":"abejojo"
         },
         "tense":"Past",
         "forms":[
            "abejojau",
            "abejojai",
            "abejojo",
            "abejojome",
            "abejojote",
            "abejojo"
         ]
      },
      {
         "verb":{
            "infinitive":"abejoti",
            "present":"abejoja",
            "past":"abejojo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "abejodavau",
            "abejodavai",
            "abejodavo",
            "abejodavome",
            "abejodavote",
            "abejodavo"
         ]
      },
      {
         "verb":{
            "infinitive":"abejoti",
            "present":"abejoja",
            "past":"abejojo"
         },
         "tense":"Future",
         "forms":[
            "abejosiu",
            "abejosi",
            "abejos",
            "abejosime",
            "abejosite",
            "abejos"
         ]
      },
      {
         "verb":{
            "infinitive":"abejoti",
            "present":"abejoja",
            "past":"abejojo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "abejok",
            "tegu abejoja",
            "abejokime",
            "abejokite",
            "tegu abejoja"
         ]
      },
      {
         "verb":{
            "infinitive":"abejoti",
            "present":"abejoja",
            "past":"abejojo"
         },
         "tense":"Conditional",
         "forms":[
            "abejočiau",
            "abejotum",
            "abejotų",
            "abejotume / abejotumėme",
            "abejotute / abejotumėte",
            "abejotų"
         ]
      }
   ],
   "aiškinti":[
      {
         "verb":{
            "infinitive":"aiškinti",
            "present":"aiškina",
            "past":"aiškino"
         },
         "tense":"Present",
         "forms":[
            "aiškinu",
            "aiškini",
            "aiškina",
            "aiškiname",
            "aiškinate",
            "aiškina"
         ]
      },
      {
         "verb":{
            "infinitive":"aiškinti",
            "present":"aiškina",
            "past":"aiškino"
         },
         "tense":"Past",
         "forms":[
            "aiškinau",
            "aiškinai",
            "aiškino",
            "aiškinome",
            "aiškinote",
            "aiškino"
         ]
      },
      {
         "verb":{
            "infinitive":"aiškinti",
            "present":"aiškina",
            "past":"aiškino"
         },
         "tense":"PastContiniuos",
         "forms":[
            "aiškindavau",
            "aiškindavai",
            "aiškindavo",
            "aiškindavome",
            "aiškindavote",
            "aiškindavo"
         ]
      },
      {
         "verb":{
            "infinitive":"aiškinti",
            "present":"aiškina",
            "past":"aiškino"
         },
         "tense":"Future",
         "forms":[
            "aiškinsiu",
            "aiškinsi",
            "aiškins",
            "aiškinsime",
            "aiškinsite",
            "aiškins"
         ]
      },
      {
         "verb":{
            "infinitive":"aiškinti",
            "present":"aiškina",
            "past":"aiškino"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "aiškink",
            "tegu aiškina",
            "aiškinkime",
            "aiškinkite",
            "tegu aiškina"
         ]
      },
      {
         "verb":{
            "infinitive":"aiškinti",
            "present":"aiškina",
            "past":"aiškino"
         },
         "tense":"Conditional",
         "forms":[
            "aiškinčiau",
            "aiškintum",
            "aiškintų",
            "aiškintume / aiškintumėme",
            "aiškintute / aiškintumėte",
            "aiškintų"
         ]
      }
   ],
   "apsistoti":[
      {
         "verb":{
            "infinitive":"apsistoti",
            "present":"apsistoja",
            "past":"apsistojo"
         },
         "tense":"Present",
         "forms":[
            "apsistoju",
            "apsistoji",
            "apsistoja",
            "apsistojame",
            "apsistojate",
            "apsistoja"
         ]
      },
      {
         "verb":{
            "infinitive":"apsistoti",
            "present":"apsistoja",
            "past":"apsistojo"
         },
         "tense":"Past",
         "forms":[
            "apsistojau",
            "apsistojai",
            "apsistojo",
            "apsistojome",
            "apsistojote",
            "apsistojo"
         ]
      },
      {
         "verb":{
            "infinitive":"apsistoti",
            "present":"apsistoja",
            "past":"apsistojo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "apsistodavau",
            "apsistodavai",
            "apsistodavo",
            "apsistodavome",
            "apsistodavote",
            "apsistodavo"
         ]
      },
      {
         "verb":{
            "infinitive":"apsistoti",
            "present":"apsistoja",
            "past":"apsistojo"
         },
         "tense":"Future",
         "forms":[
            "apsistosiu",
            "apsistosi",
            "apsistos",
            "apsistosime",
            "apsistosite",
            "apsistos"
         ]
      },
      {
         "verb":{
            "infinitive":"apsistoti",
            "present":"apsistoja",
            "past":"apsistojo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "apsistok",
            "tegu apsistoja",
            "apsistokime",
            "apsistokite",
            "tegu apsistoja"
         ]
      },
      {
         "verb":{
            "infinitive":"apsistoti",
            "present":"apsistoja",
            "past":"apsistojo"
         },
         "tense":"Conditional",
         "forms":[
            "apsistočiau",
            "apsistotum",
            "apsistotų",
            "apsistotume / apsistotumėme",
            "apsistotute / apsistotumėte",
            "apsistotų"
         ]
      }
   ],
   "atleisti":[
      {
         "verb":{
            "infinitive":"atleisti",
            "present":"atleidžia",
            "past":"atleido"
         },
         "tense":"Present",
         "forms":[
            "atleidžiu",
            "atleidži",
            "atleidžia",
            "atleidžiame",
            "atleidžiate",
            "atleidžia"
         ]
      },
      {
         "verb":{
            "infinitive":"atleisti",
            "present":"atleidžia",
            "past":"atleido"
         },
         "tense":"Past",
         "forms":[
            "atleidau",
            "atleidai",
            "atleido",
            "atleidome",
            "atleidote",
            "atleido"
         ]
      },
      {
         "verb":{
            "infinitive":"atleisti",
            "present":"atleidžia",
            "past":"atleido"
         },
         "tense":"PastContiniuos",
         "forms":[
            "atleisdavau",
            "atleisdavai",
            "atleisdavo",
            "atleisdavome",
            "atleisdavote",
            "atleisdavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atleisti",
            "present":"atleidžia",
            "past":"atleido"
         },
         "tense":"Future",
         "forms":[
            "atleisiu",
            "atleisi",
            "atleis",
            "atleisime",
            "atleisite",
            "atleis"
         ]
      },
      {
         "verb":{
            "infinitive":"atleisti",
            "present":"atleidžia",
            "past":"atleido"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "atleisk",
            "tegu atleidžia",
            "atleiskime",
            "atleiskite",
            "tegu atleidžia"
         ]
      },
      {
         "verb":{
            "infinitive":"atleisti",
            "present":"atleidžia",
            "past":"atleido"
         },
         "tense":"Conditional",
         "forms":[
            "atleisčiau",
            "atleistum",
            "atleistų",
            "atleistume / atleistumėme",
            "atleistute / atleistumėte",
            "atleistų"
         ]
      }
   ],
   "atostogauti":[
      {
         "verb":{
            "infinitive":"atostogauti",
            "present":"atostogauja",
            "past":"atostogavo"
         },
         "tense":"Present",
         "forms":[
            "atostogauju",
            "atostogauji",
            "atostogauja",
            "atostogaujame",
            "atostogaujate",
            "atostogauja"
         ]
      },
      {
         "verb":{
            "infinitive":"atostogauti",
            "present":"atostogauja",
            "past":"atostogavo"
         },
         "tense":"Past",
         "forms":[
            "atostogavau",
            "atostogavai",
            "atostogavo",
            "atostogavome",
            "atostogavote",
            "atostogavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atostogauti",
            "present":"atostogauja",
            "past":"atostogavo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "atostogaudavau",
            "atostogaudavai",
            "atostogaudavo",
            "atostogaudavome",
            "atostogaudavote",
            "atostogaudavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atostogauti",
            "present":"atostogauja",
            "past":"atostogavo"
         },
         "tense":"Future",
         "forms":[
            "atostogausiu",
            "atostogausi",
            "atostogaus",
            "atostogausime",
            "atostogausite",
            "atostogaus"
         ]
      },
      {
         "verb":{
            "infinitive":"atostogauti",
            "present":"atostogauja",
            "past":"atostogavo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "atostogauk",
            "tegu atostogauja",
            "atostogaukime",
            "atostogaukite",
            "tegu atostogauja"
         ]
      },
      {
         "verb":{
            "infinitive":"atostogauti",
            "present":"atostogauja",
            "past":"atostogavo"
         },
         "tense":"Conditional",
         "forms":[
            "atostogaučiau",
            "atostogautum",
            "atostogautų",
            "atostogautume / atostogautumėme",
            "atostogautute / atostogautumėte",
            "atostogautų"
         ]
      }
   ],
   "atrodyti":[
      {
         "verb":{
            "infinitive":"atrodyti",
            "present":"atrodo",
            "past":"atrodė"
         },
         "tense":"Present",
         "forms":[
            "atrodau",
            "atrodai",
            "atrodo",
            "atrodome",
            "atrodote",
            "atrodo"
         ]
      },
      {
         "verb":{
            "infinitive":"atrodyti",
            "present":"atrodo",
            "past":"atrodė"
         },
         "tense":"Past",
         "forms":[
            "atrodžiau",
            "atrodei",
            "atrodė",
            "atrodėme",
            "atrodėte",
            "atrodė"
         ]
      },
      {
         "verb":{
            "infinitive":"atrodyti",
            "present":"atrodo",
            "past":"atrodė"
         },
         "tense":"PastContiniuos",
         "forms":[
            "atrodydavau",
            "atrodydavai",
            "atrodydavo",
            "atrodydavome",
            "atrodydavote",
            "atrodydavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atrodyti",
            "present":"atrodo",
            "past":"atrodė"
         },
         "tense":"Future",
         "forms":[
            "atrodysiu",
            "atrodysi",
            "atrodys",
            "atrodysime",
            "atrodysite",
            "atrodys"
         ]
      },
      {
         "verb":{
            "infinitive":"atrodyti",
            "present":"atrodo",
            "past":"atrodė"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "atrodyk",
            "tegu atrodo",
            "atrodykime",
            "atrodykite",
            "tegu atrodo"
         ]
      },
      {
         "verb":{
            "infinitive":"atrodyti",
            "present":"atrodo",
            "past":"atrodė"
         },
         "tense":"Conditional",
         "forms":[
            "atrodyčiau",
            "atrodytum",
            "atrodytų",
            "atrodytume / atrodytumėme",
            "atrodytute / atrodytumėte",
            "atrodytų"
         ]
      }
   ],
   "atsakyti":[
      {
         "verb":{
            "infinitive":"atsakyti",
            "present":"atsako",
            "past":"atsakė"
         },
         "tense":"Present",
         "forms":[
            "atsakau",
            "atsakai",
            "atsako",
            "atsakome",
            "atsakote",
            "atsako"
         ]
      },
      {
         "verb":{
            "infinitive":"atsakyti",
            "present":"atsako",
            "past":"atsakė"
         },
         "tense":"Past",
         "forms":[
            "atsakiau",
            "atsakei",
            "atsakė",
            "atsakėme",
            "atsakėte",
            "atsakė"
         ]
      },
      {
         "verb":{
            "infinitive":"atsakyti",
            "present":"atsako",
            "past":"atsakė"
         },
         "tense":"PastContiniuos",
         "forms":[
            "atsakydavau",
            "atsakydavai",
            "atsakydavo",
            "atsakydavome",
            "atsakydavote",
            "atsakydavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atsakyti",
            "present":"atsako",
            "past":"atsakė"
         },
         "tense":"Future",
         "forms":[
            "atsakysiu",
            "atsakysi",
            "atsakys",
            "atsakysime",
            "atsakysite",
            "atsakys"
         ]
      },
      {
         "verb":{
            "infinitive":"atsakyti",
            "present":"atsako",
            "past":"atsakė"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "atsakyk",
            "tegu atsako",
            "atsakykime",
            "atsakykite",
            "tegu atsako"
         ]
      },
      {
         "verb":{
            "infinitive":"atsakyti",
            "present":"atsako",
            "past":"atsakė"
         },
         "tense":"Conditional",
         "forms":[
            "atsakyčiau",
            "atsakytum",
            "atsakytų",
            "atsakytume / atsakytumėme",
            "atsakytute / atsakytumėte",
            "atsakytų"
         ]
      }
   ],
   "atsiliepti":[
      {
         "verb":{
            "infinitive":"atsiliepti",
            "present":"atsiliepia",
            "past":"atsiliepė"
         },
         "tense":"Present",
         "forms":[
            "atsiliepiu",
            "atsiliepi",
            "atsiliepia",
            "atsiliepiame",
            "atsiliepiate",
            "atsiliepia"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiliepti",
            "present":"atsiliepia",
            "past":"atsiliepė"
         },
         "tense":"Past",
         "forms":[
            "atsiliepiau",
            "atsiliepei",
            "atsiliepė",
            "atsiliepėme",
            "atsiliepėte",
            "atsiliepė"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiliepti",
            "present":"atsiliepia",
            "past":"atsiliepė"
         },
         "tense":"PastContiniuos",
         "forms":[
            "atsiliepdavau",
            "atsiliepdavai",
            "atsiliepdavo",
            "atsiliepdavome",
            "atsiliepdavote",
            "atsiliepdavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiliepti",
            "present":"atsiliepia",
            "past":"atsiliepė"
         },
         "tense":"Future",
         "forms":[
            "atsiliepsiu",
            "atsiliepsi",
            "atsilieps",
            "atsiliepsime",
            "atsiliepsite",
            "atsilieps"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiliepti",
            "present":"atsiliepia",
            "past":"atsiliepė"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "atsiliepk",
            "tegu atsiliepia",
            "atsiliepkime",
            "atsiliepkite",
            "tegu atsiliepia"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiliepti",
            "present":"atsiliepia",
            "past":"atsiliepė"
         },
         "tense":"Conditional",
         "forms":[
            "atsiliepčiau",
            "atsilieptum",
            "atsilieptų",
            "atsilieptume / atsilieptumėme",
            "atsilieptute / atsilieptumėte",
            "atsilieptų"
         ]
      }
   ],
   "atsiminti":[
      {
         "verb":{
            "infinitive":"atsiminti",
            "present":"atsimena",
            "past":"atsiminė"
         },
         "tense":"Present",
         "forms":[
            "atsimenu",
            "atsimeni",
            "atsimena",
            "atsimename",
            "atsimenate",
            "atsimena"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiminti",
            "present":"atsimena",
            "past":"atsiminė"
         },
         "tense":"Past",
         "forms":[
            "atsiminiau",
            "atsiminei",
            "atsiminė",
            "atsiminėme",
            "atsiminėte",
            "atsiminė"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiminti",
            "present":"atsimena",
            "past":"atsiminė"
         },
         "tense":"PastContiniuos",
         "forms":[
            "atsimindavau",
            "atsimindavai",
            "atsimindavo",
            "atsimindavome",
            "atsimindavote",
            "atsimindavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiminti",
            "present":"atsimena",
            "past":"atsiminė"
         },
         "tense":"Future",
         "forms":[
            "atsiminsiu",
            "atsiminsi",
            "atsimins",
            "atsiminsime",
            "atsiminsite",
            "atsimins"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiminti",
            "present":"atsimena",
            "past":"atsiminė"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "atsimink",
            "tegu atsimena",
            "atsiminkime",
            "atsiminkite",
            "tegu atsimena"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiminti",
            "present":"atsimena",
            "past":"atsiminė"
         },
         "tense":"Conditional",
         "forms":[
            "atsiminčiau",
            "atsimintum",
            "atsimintų",
            "atsimintume / atsimintumėme",
            "atsimintute / atsimintumėte",
            "atsimintų"
         ]
      }
   ],
   "atsiprašyti":[
      {
         "verb":{
            "infinitive":"atsiprašyti",
            "present":"atsiprašo",
            "past":"atsiprašė"
         },
         "tense":"Present",
         "forms":[
            "atsiprašau",
            "atsiprašai",
            "atsiprašo",
            "atsiprašome",
            "atsiprašote",
            "atsiprašo"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiprašyti",
            "present":"atsiprašo",
            "past":"atsiprašė"
         },
         "tense":"Past",
         "forms":[
            "atsiprašiau",
            "atsiprašei",
            "atsiprašė",
            "atsiprašėme",
            "atsiprašėte",
            "atsiprašė"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiprašyti",
            "present":"atsiprašo",
            "past":"atsiprašė"
         },
         "tense":"PastContiniuos",
         "forms":[
            "atsiprašydavau",
            "atsiprašydavai",
            "atsiprašydavo",
            "atsiprašydavome",
            "atsiprašydavote",
            "atsiprašydavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiprašyti",
            "present":"atsiprašo",
            "past":"atsiprašė"
         },
         "tense":"Future",
         "forms":[
            "atsiprašysiu",
            "atsiprašysi",
            "atsiprašys",
            "atsiprašysime",
            "atsiprašysite",
            "atsiprašys"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiprašyti",
            "present":"atsiprašo",
            "past":"atsiprašė"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "atsiprašyk",
            "tegu atsiprašo",
            "atsiprašykime",
            "atsiprašykite",
            "tegu atsiprašo"
         ]
      },
      {
         "verb":{
            "infinitive":"atsiprašyti",
            "present":"atsiprašo",
            "past":"atsiprašė"
         },
         "tense":"Conditional",
         "forms":[
            "atsiprašyčiau",
            "atsiprašytum",
            "atsiprašytų",
            "atsiprašytume / atsiprašytumėme",
            "atsiprašytute / atsiprašytumėte",
            "atsiprašytų"
         ]
      }
   ],
   "atsisakyti":[
      {
         "verb":{
            "infinitive":"atsisakyti",
            "present":"atsisako",
            "past":"atsisakė"
         },
         "tense":"Present",
         "forms":[
            "atsisakau",
            "atsisakai",
            "atsisako",
            "atsisakome",
            "atsisakote",
            "atsisako"
         ]
      },
      {
         "verb":{
            "infinitive":"atsisakyti",
            "present":"atsisako",
            "past":"atsisakė"
         },
         "tense":"Past",
         "forms":[
            "atsisakiau",
            "atsisakei",
            "atsisakė",
            "atsisakėme",
            "atsisakėte",
            "atsisakė"
         ]
      },
      {
         "verb":{
            "infinitive":"atsisakyti",
            "present":"atsisako",
            "past":"atsisakė"
         },
         "tense":"PastContiniuos",
         "forms":[
            "atsisakydavau",
            "atsisakydavai",
            "atsisakydavo",
            "atsisakydavome",
            "atsisakydavote",
            "atsisakydavo"
         ]
      },
      {
         "verb":{
            "infinitive":"atsisakyti",
            "present":"atsisako",
            "past":"atsisakė"
         },
         "tense":"Future",
         "forms":[
            "atsisakysiu",
            "atsisakysi",
            "atsisakys",
            "atsisakysime",
            "atsisakysite",
            "atsisakys"
         ]
      },
      {
         "verb":{
            "infinitive":"atsisakyti",
            "present":"atsisako",
            "past":"atsisakė"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "atsisakyk",
            "tegu atsisako",
            "atsisakykime",
            "atsisakykite",
            "tegu atsisako"
         ]
      },
      {
         "verb":{
            "infinitive":"atsisakyti",
            "present":"atsisako",
            "past":"atsisakė"
         },
         "tense":"Conditional",
         "forms":[
            "atsisakyčiau",
            "atsisakytum",
            "atsisakytų",
            "atsisakytume / atsisakytumėme",
            "atsisakytute / atsisakytumėte",
            "atsisakytų"
         ]
      }
   ],
   "auginti":[
      {
         "verb":{
            "infinitive":"auginti",
            "present":"augina",
            "past":"augino"
         },
         "tense":"Present",
         "forms":[
            "auginu",
            "augini",
            "augina",
            "auginame",
            "auginate",
            "augina"
         ]
      },
      {
         "verb":{
            "infinitive":"auginti",
            "present":"augina",
            "past":"augino"
         },
         "tense":"Past",
         "forms":[
            "auginau",
            "auginai",
            "augino",
            "auginome",
            "auginote",
            "augino"
         ]
      },
      {
         "verb":{
            "infinitive":"auginti",
            "present":"augina",
            "past":"augino"
         },
         "tense":"PastContiniuos",
         "forms":[
            "augindavau",
            "augindavai",
            "augindavo",
            "augindavome",
            "augindavote",
            "augindavo"
         ]
      },
      {
         "verb":{
            "infinitive":"auginti",
            "present":"augina",
            "past":"augino"
         },
         "tense":"Future",
         "forms":[
            "auginsiu",
            "auginsi",
            "augins",
            "auginsime",
            "auginsite",
            "augins"
         ]
      },
      {
         "verb":{
            "infinitive":"auginti",
            "present":"augina",
            "past":"augino"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "augink",
            "tegu augina",
            "auginkime",
            "auginkite",
            "tegu augina"
         ]
      },
      {
         "verb":{
            "infinitive":"auginti",
            "present":"augina",
            "past":"augino"
         },
         "tense":"Conditional",
         "forms":[
            "auginčiau",
            "augintum",
            "augintų",
            "augintume / augintumėme",
            "augintute / augintumėte",
            "augintų"
         ]
      }
   ],
   "augti":[
      {
         "verb":{
            "infinitive":"augti",
            "present":"auga",
            "past":"augo"
         },
         "tense":"Present",
         "forms":[
            "augu",
            "augi",
            "auga",
            "augame",
            "augate",
            "auga"
         ]
      },
      {
         "verb":{
            "infinitive":"augti",
            "present":"auga",
            "past":"augo"
         },
         "tense":"Past",
         "forms":[
            "augau",
            "augai",
            "augo",
            "augome",
            "augote",
            "augo"
         ]
      },
      {
         "verb":{
            "infinitive":"augti",
            "present":"auga",
            "past":"augo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "augdavau",
            "augdavai",
            "augdavo",
            "augdavome",
            "augdavote",
            "augdavo"
         ]
      },
      {
         "verb":{
            "infinitive":"augti",
            "present":"auga",
            "past":"augo"
         },
         "tense":"Future",
         "forms":[
            "augsiu",
            "augsi",
            "augs",
            "augsime",
            "augsite",
            "augs"
         ]
      },
      {
         "verb":{
            "infinitive":"augti",
            "present":"auga",
            "past":"augo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "auk",
            "tegu auga",
            "aukime",
            "aukite",
            "tegu auga"
         ]
      },
      {
         "verb":{
            "infinitive":"augti",
            "present":"auga",
            "past":"augo"
         },
         "tense":"Conditional",
         "forms":[
            "augčiau",
            "augtum",
            "augtų",
            "augtume / augtumėme",
            "augtute / augtumėte",
            "augtų"
         ]
      }
   ],
   "auklėti":[
      {
         "verb":{
            "infinitive":"auklėti",
            "present":"auklėja",
            "past":"auklėjo"
         },
         "tense":"Present",
         "forms":[
            "auklėju",
            "auklėji",
            "auklėja",
            "auklėjame",
            "auklėjate",
            "auklėja"
         ]
      },
      {
         "verb":{
            "infinitive":"auklėti",
            "present":"auklėja",
            "past":"auklėjo"
         },
         "tense":"Past",
         "forms":[
            "auklėjau",
            "auklėjai",
            "auklėjo",
            "auklėjome",
            "auklėjote",
            "auklėjo"
         ]
      },
      {
         "verb":{
            "infinitive":"auklėti",
            "present":"auklėja",
            "past":"auklėjo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "auklėdavau",
            "auklėdavai",
            "auklėdavo",
            "auklėdavome",
            "auklėdavote",
            "auklėdavo"
         ]
      },
      {
         "verb":{
            "infinitive":"auklėti",
            "present":"auklėja",
            "past":"auklėjo"
         },
         "tense":"Future",
         "forms":[
            "auklėsiu",
            "auklėsi",
            "auklės",
            "auklėsime",
            "auklėsite",
            "auklės"
         ]
      },
      {
         "verb":{
            "infinitive":"auklėti",
            "present":"auklėja",
            "past":"auklėjo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "auklėk",
            "tegu auklėja",
            "auklėkime",
            "auklėkite",
            "tegu auklėja"
         ]
      },
      {
         "verb":{
            "infinitive":"auklėti",
            "present":"auklėja",
            "past":"auklėjo"
         },
         "tense":"Conditional",
         "forms":[
            "auklėčiau",
            "auklėtum",
            "auklėtų",
            "auklėtume / auklėtumėme",
            "auklėtute / auklėtumėte",
            "auklėtų"
         ]
      }
   ],
   "autis":[
      {
         "verb":{
            "infinitive":"autis",
            "present":"aunasi",
            "past":"avėsi"
         },
         "tense":"Present",
         "forms":[
            "aunuosi",
            "auniesi",
            "aunasi",
            "aunamės",
            "aunatės",
            "aunasi"
         ]
      },
      {
         "verb":{
            "infinitive":"autis",
            "present":"aunasi",
            "past":"avėsi"
         },
         "tense":"Past",
         "forms":[
            "aviausi",
            "aveisi",
            "avėsi",
            "avėmės",
            "avėtės",
            "avėsi"
         ]
      },
      {
         "verb":{
            "infinitive":"autis",
            "present":"aunasi",
            "past":"avėsi"
         },
         "tense":"PastContiniuos",
         "forms":[
            "audavausi",
            "audavaisi",
            "audavosi",
            "audavomės",
            "audavotės",
            "audavosi"
         ]
      },
      {
         "verb":{
            "infinitive":"autis",
            "present":"aunasi",
            "past":"avėsi"
         },
         "tense":"Future",
         "forms":[
            "ausiuosi",
            "ausiesi",
            "ausis",
            "ausimės",
            "ausitės",
            "ausis"
         ]
      },
      {
         "verb":{
            "infinitive":"autis",
            "present":"aunasi",
            "past":"avėsi"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "aukis",
            "tegu aunasi / tesiauna",
            "aukimės",
            "aukitės",
            "tegu aunasi / tesiauna"
         ]
      },
      {
         "verb":{
            "infinitive":"autis",
            "present":"aunasi",
            "past":"avėsi"
         },
         "tense":"Conditional",
         "forms":[
            "aučiausi",
            "autumeisi",
            "autųsi",
            "autumės / autumėmės",
            "aututės / autumėtės",
            "autųsi"
         ]
      }
   ],
   "baigti":[
      {
         "verb":{
            "infinitive":"baigti",
            "present":"baigia",
            "past":"baigė"
         },
         "tense":"Present",
         "forms":[
            "baigiu",
            "baigi",
            "baigia",
            "baigiame",
            "baigiate",
            "baigia"
         ]
      },
      {
         "verb":{
            "infinitive":"baigti",
            "present":"baigia",
            "past":"baigė"
         },
         "tense":"Past",
         "forms":[
            "baigiau",
            "baigei",
            "baigė",
            "baigėme",
            "baigėte",
            "baigė"
         ]
      },
      {
         "verb":{
            "infinitive":"baigti",
            "present":"baigia",
            "past":"baigė"
         },
         "tense":"PastContiniuos",
         "forms":[
            "baigdavau",
            "baigdavai",
            "baigdavo",
            "baigdavome",
            "baigdavote",
            "baigdavo"
         ]
      },
      {
         "verb":{
            "infinitive":"baigti",
            "present":"baigia",
            "past":"baigė"
         },
         "tense":"Future",
         "forms":[
            "baigsiu",
            "baigsi",
            "baigs",
            "baigsime",
            "baigsite",
            "baigs"
         ]
      },
      {
         "verb":{
            "infinitive":"baigti",
            "present":"baigia",
            "past":"baigė"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "baik",
            "tegu baigia",
            "baikime",
            "baikite",
            "tegu baigia"
         ]
      },
      {
         "verb":{
            "infinitive":"baigti",
            "present":"baigia",
            "past":"baigė"
         },
         "tense":"Conditional",
         "forms":[
            "baigčiau",
            "baigtum",
            "baigtų",
            "baigtume / baigtumėme",
            "baigtute / baigtumėte",
            "baigtų"
         ]
      }
   ],
   "eiti":[
      {
         "verb":{
            "infinitive":"eiti",
            "present":"eina",
            "past":"ėjo"
         },
         "tense":"Present",
         "forms":[
            "einu",
            "eini",
            "eina",
            "einame",
            "einate",
            "eina"
         ]
      },
      {
         "verb":{
            "infinitive":"eiti",
            "present":"eina",
            "past":"ėjo"
         },
         "tense":"Past",
         "forms":[
            "ėjau",
            "ėjai",
            "ėjo",
            "ėjome",
            "ėjote",
            "ėjo"
         ]
      },
      {
         "verb":{
            "infinitive":"eiti",
            "present":"eina",
            "past":"ėjo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "eidavau",
            "eidavai",
            "eidavo",
            "eidavome",
            "eidavote",
            "eidavo"
         ]
      },
      {
         "verb":{
            "infinitive":"eiti",
            "present":"eina",
            "past":"ėjo"
         },
         "tense":"Future",
         "forms":[
            "eisiu",
            "eisi",
            "eis",
            "eisime",
            "eisite",
            "eis"
         ]
      },
      {
         "verb":{
            "infinitive":"eiti",
            "present":"eina",
            "past":"ėjo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "eik",
            "tegu eina",
            "eikime",
            "eikite",
            "tegu eina"
         ]
      },
      {
         "verb":{
            "infinitive":"eiti",
            "present":"eina",
            "past":"ėjo"
         },
         "tense":"Conditional",
         "forms":[
            "eičiau",
            "eitum",
            "eitų",
            "eitume / eitumėme",
            "eitute / eitumėte",
            "eitų"
         ]
      }
   ],
   "baigtis":[
      {
         "verb":{
            "infinitive":"baigtis",
            "present":"baigiasi",
            "past":"baigėsi"
         },
         "tense":"Present",
         "forms":[
            "baigiuosi",
            "baigiesi",
            "baigiasi",
            "baigiamės",
            "baigiatės",
            "baigiasi"
         ]
      },
      {
         "verb":{
            "infinitive":"baigtis",
            "present":"baigiasi",
            "past":"baigėsi"
         },
         "tense":"Past",
         "forms":[
            "baigiausi",
            "baigeisi",
            "baigėsi",
            "baigėmės",
            "baigėtės",
            "baigėsi"
         ]
      },
      {
         "verb":{
            "infinitive":"baigtis",
            "present":"baigiasi",
            "past":"baigėsi"
         },
         "tense":"PastContiniuos",
         "forms":[
            "baigdavausi",
            "baigdavaisi",
            "baigdavosi",
            "baigdavomės",
            "baigdavotės",
            "baigdavosi"
         ]
      },
      {
         "verb":{
            "infinitive":"baigtis",
            "present":"baigiasi",
            "past":"baigėsi"
         },
         "tense":"Future",
         "forms":[
            "baigsiuosi",
            "baigsiesi",
            "baigsis",
            "baigsimės",
            "baigsitės",
            "baigsis"
         ]
      },
      {
         "verb":{
            "infinitive":"baigtis",
            "present":"baigiasi",
            "past":"baigėsi"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "baikis",
            "tegu baigiasi / tesibaigia",
            "baikimės",
            "baikitės",
            "tegu baigiasi / tesibaigia"
         ]
      },
      {
         "verb":{
            "infinitive":"baigtis",
            "present":"baigiasi",
            "past":"baigėsi"
         },
         "tense":"Conditional",
         "forms":[
            "baigčiausi",
            "baigtumeisi",
            "baigtųsi",
            "baigtumės / baigtumėmės",
            "baigtutės / baigtumėtės",
            "baigtųsi"
         ]
      }
   ],
   "bandyti":[
      {
         "verb":{
            "infinitive":"bandyti",
            "present":"bando",
            "past":"bandė"
         },
         "tense":"Present",
         "forms":[
            "bandau",
            "bandai",
            "bando",
            "bandome",
            "bandote",
            "bando"
         ]
      },
      {
         "verb":{
            "infinitive":"bandyti",
            "present":"bando",
            "past":"bandė"
         },
         "tense":"Past",
         "forms":[
            "bandžiau",
            "bandei",
            "bandė",
            "bandėme",
            "bandėte",
            "bandė"
         ]
      },
      {
         "verb":{
            "infinitive":"bandyti",
            "present":"bando",
            "past":"bandė"
         },
         "tense":"PastContiniuos",
         "forms":[
            "bandydavau",
            "bandydavai",
            "bandydavo",
            "bandydavome",
            "bandydavote",
            "bandydavo"
         ]
      },
      {
         "verb":{
            "infinitive":"bandyti",
            "present":"bando",
            "past":"bandė"
         },
         "tense":"Future",
         "forms":[
            "bandysiu",
            "bandysi",
            "bandys",
            "bandysime",
            "bandysite",
            "bandys"
         ]
      },
      {
         "verb":{
            "infinitive":"bandyti",
            "present":"bando",
            "past":"bandė"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "bandyk",
            "tegu bando",
            "bandykime",
            "bandykite",
            "tegu bando"
         ]
      },
      {
         "verb":{
            "infinitive":"bandyti",
            "present":"bando",
            "past":"bandė"
         },
         "tense":"Conditional",
         "forms":[
            "bandyčiau",
            "bandytum",
            "bandytų",
            "bandytume / bandytumėme",
            "bandytute / bandytumėte",
            "bandytų"
         ]
      }
   ],
   "bėgioti":[
      {
         "verb":{
            "infinitive":"bėgioti",
            "present":"bėgioja",
            "past":"bėgiojo"
         },
         "tense":"Present",
         "forms":[
            "bėgioju",
            "bėgioji",
            "bėgioja",
            "bėgiojame",
            "bėgiojate",
            "bėgioja"
         ]
      },
      {
         "verb":{
            "infinitive":"bėgioti",
            "present":"bėgioja",
            "past":"bėgiojo"
         },
         "tense":"Past",
         "forms":[
            "bėgiojau",
            "bėgiojai",
            "bėgiojo",
            "bėgiojome",
            "bėgiojote",
            "bėgiojo"
         ]
      },
      {
         "verb":{
            "infinitive":"bėgioti",
            "present":"bėgioja",
            "past":"bėgiojo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "bėgiodavau",
            "bėgiodavai",
            "bėgiodavo",
            "bėgiodavome",
            "bėgiodavote",
            "bėgiodavo"
         ]
      },
      {
         "verb":{
            "infinitive":"bėgioti",
            "present":"bėgioja",
            "past":"bėgiojo"
         },
         "tense":"Future",
         "forms":[
            "bėgiosiu",
            "bėgiosi",
            "bėgios",
            "bėgiosime",
            "bėgiosite",
            "bėgios"
         ]
      },
      {
         "verb":{
            "infinitive":"bėgioti",
            "present":"bėgioja",
            "past":"bėgiojo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "bėgiok",
            "tegu bėgioja",
            "bėgiokime",
            "bėgiokite",
            "tegu bėgioja"
         ]
      },
      {
         "verb":{
            "infinitive":"bėgioti",
            "present":"bėgioja",
            "past":"bėgiojo"
         },
         "tense":"Conditional",
         "forms":[
            "bėgiočiau",
            "bėgiotum",
            "bėgiotų",
            "bėgiotume / bėgiotumėme",
            "bėgiotute / bėgiotumėte",
            "bėgiotų"
         ]
      }
   ],
   "bėgti":[
      {
         "verb":{
            "infinitive":"bėgti",
            "present":"bėga",
            "past":"bėgo"
         },
         "tense":"Present",
         "forms":[
            "bėgu",
            "bėgi",
            "bėga",
            "bėgame",
            "bėgate",
            "bėga"
         ]
      },
      {
         "verb":{
            "infinitive":"bėgti",
            "present":"bėga",
            "past":"bėgo"
         },
         "tense":"Past",
         "forms":[
            "bėgau",
            "bėgai",
            "bėgo",
            "bėgome",
            "bėgote",
            "bėgo"
         ]
      },
      {
         "verb":{
            "infinitive":"bėgti",
            "present":"bėga",
            "past":"bėgo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "bėgdavau",
            "bėgdavai",
            "bėgdavo",
            "bėgdavome",
            "bėgdavote",
            "bėgdavo"
         ]
      },
      {
         "verb":{
            "infinitive":"bėgti",
            "present":"bėga",
            "past":"bėgo"
         },
         "tense":"Future",
         "forms":[
            "bėgsiu",
            "bėgsi",
            "bėgs",
            "bėgsime",
            "bėgsite",
            "bėgs"
         ]
      },
      {
         "verb":{
            "infinitive":"bėgti",
            "present":"bėga",
            "past":"bėgo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "bėk",
            "tegu bėga",
            "bėkime",
            "bėkite",
            "tegu bėga"
         ]
      },
      {
         "verb":{
            "infinitive":"bėgti",
            "present":"bėga",
            "past":"bėgo"
         },
         "tense":"Conditional",
         "forms":[
            "bėgčiau",
            "bėgtum",
            "bėgtų",
            "bėgtume / bėgtumėme",
            "bėgtute / bėgtumėte",
            "bėgtų"
         ]
      }
   ],
   "bijoti":[
      {
         "verb":{
            "infinitive":"bijoti",
            "present":"bijo",
            "past":"bijojo"
         },
         "tense":"Present",
         "forms":[
            "bijau",
            "bijai",
            "bijo",
            "bijome",
            "bijote",
            "bijo"
         ]
      },
      {
         "verb":{
            "infinitive":"bijoti",
            "present":"bijo",
            "past":"bijojo"
         },
         "tense":"Past",
         "forms":[
            "bijojau",
            "bijojai",
            "bijojo",
            "bijojome",
            "bijojote",
            "bijojo"
         ]
      },
      {
         "verb":{
            "infinitive":"bijoti",
            "present":"bijo",
            "past":"bijojo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "bijodavau",
            "bijodavai",
            "bijodavo",
            "bijodavome",
            "bijodavote",
            "bijodavo"
         ]
      },
      {
         "verb":{
            "infinitive":"bijoti",
            "present":"bijo",
            "past":"bijojo"
         },
         "tense":"Future",
         "forms":[
            "bijosiu",
            "bijosi",
            "bijos",
            "bijosime",
            "bijosite",
            "bijos"
         ]
      },
      {
         "verb":{
            "infinitive":"bijoti",
            "present":"bijo",
            "past":"bijojo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "bijok",
            "tegu bijo",
            "bijokime",
            "bijokite",
            "tegu bijo"
         ]
      },
      {
         "verb":{
            "infinitive":"bijoti",
            "present":"bijo",
            "past":"bijojo"
         },
         "tense":"Conditional",
         "forms":[
            "bijočiau",
            "bijotum",
            "bijotų",
            "bijotume / bijotumėme",
            "bijotute / bijotumėte",
            "bijotų"
         ]
      }
   ],
   "bičiuoti":[
      {
         "verb":{
            "infinitive":"bučiuoti",
            "present":"bučiuoja",
            "past":"bučiavo"
         },
         "tense":"Present",
         "forms":[
            "bučiuoju",
            "bučiuoji",
            "bučiuoja",
            "bučiuojame",
            "bučiuojate",
            "bučiuoja"
         ]
      },
      {
         "verb":{
            "infinitive":"bučiuoti",
            "present":"bučiuoja",
            "past":"bučiavo"
         },
         "tense":"Past",
         "forms":[
            "bučiavau",
            "bučiavai",
            "bučiavo",
            "bučiavome",
            "bučiavote",
            "bučiavo"
         ]
      },
      {
         "verb":{
            "infinitive":"bučiuoti",
            "present":"bučiuoja",
            "past":"bučiavo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "bučiuodavau",
            "bučiuodavai",
            "bučiuodavo",
            "bučiuodavome",
            "bučiuodavote",
            "bučiuodavo"
         ]
      },
      {
         "verb":{
            "infinitive":"bučiuoti",
            "present":"bučiuoja",
            "past":"bučiavo"
         },
         "tense":"Future",
         "forms":[
            "bučiuosiu",
            "bučiuosi",
            "bučiuos",
            "bučiuosime",
            "bučiuosite",
            "bučiuos"
         ]
      },
      {
         "verb":{
            "infinitive":"bučiuoti",
            "present":"bučiuoja",
            "past":"bučiavo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "bučiuok",
            "tegu bučiuoja",
            "bučiuokime",
            "bučiuokite",
            "tegu bučiuoja"
         ]
      },
      {
         "verb":{
            "infinitive":"bučiuoti",
            "present":"bučiuoja",
            "past":"bučiavo"
         },
         "tense":"Conditional",
         "forms":[
            "bučiuočiau",
            "bučiuotum",
            "bučiuotų",
            "bučiuotume / bučiuotumėme",
            "bučiuotute / bučiuotumėte",
            "bučiuotų"
         ]
      }
   ],
   "bučiuotis":[
      {
         "verb":{
            "infinitive":"bučiuotis",
            "present":"bučiuojasi",
            "past":"bučiavosi"
         },
         "tense":"Present",
         "forms":[
            "bučiuojuosi",
            "bučiuojiesi",
            "bučiuojasi",
            "bučiuojamės",
            "bučiuojatės",
            "bučiuojasi"
         ]
      },
      {
         "verb":{
            "infinitive":"bučiuotis",
            "present":"bučiuojasi",
            "past":"bučiavosi"
         },
         "tense":"Past",
         "forms":[
            "bučiavausi",
            "bučiavaisi",
            "bučiavosi",
            "bučiavomės",
            "bučiavotės",
            "bučiavosi"
         ]
      },
      {
         "verb":{
            "infinitive":"bučiuotis",
            "present":"bučiuojasi",
            "past":"bučiavosi"
         },
         "tense":"PastContiniuos",
         "forms":[
            "bučiuodavausi",
            "bučiuodavaisi",
            "bučiuodavosi",
            "bučiuodavomės",
            "bučiuodavotės",
            "bučiuodavosi"
         ]
      },
      {
         "verb":{
            "infinitive":"bučiuotis",
            "present":"bučiuojasi",
            "past":"bučiavosi"
         },
         "tense":"Future",
         "forms":[
            "bučiuosiuosi",
            "bučiuosiesi",
            "bučiuosis",
            "bučiuosimės",
            "bučiuositės",
            "bučiuosis"
         ]
      },
      {
         "verb":{
            "infinitive":"bučiuotis",
            "present":"bučiuojasi",
            "past":"bučiavosi"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "bučiuokis",
            "tegu bučiuojasi / tesibučiuoja",
            "bučiuokimės",
            "bučiuokitės",
            "tegu bučiuojasi / tesibučiuoja"
         ]
      },
      {
         "verb":{
            "infinitive":"bučiuotis",
            "present":"bučiuojasi",
            "past":"bučiavosi"
         },
         "tense":"Conditional",
         "forms":[
            "bučiuočiausi",
            "bučiuotumeisi",
            "bučiuotųsi",
            "bučiuotumės / bučiuotumėmės",
            "bučiuotutės / bučiuotumėtės",
            "bučiuotųsi"
         ]
      }
   ],
   "būti":[
      {
         "verb":{
            "infinitive":"būti",
            "present":"yra",
            "past":"buvo"
         },
         "tense":"Present",
         "forms":[
            "esu / būnu",
            "esi / būni",
            "yra / būna",
            "esame / būname",
            "esate / būnate",
            "yra / būna"
         ]
      },
      {
         "verb":{
            "infinitive":"būti",
            "present":"yra",
            "past":"buvo"
         },
         "tense":"Past",
         "forms":[
            "buvau",
            "buvai",
            "buvo",
            "buvome",
            "buvote",
            "buvo"
         ]
      },
      {
         "verb":{
            "infinitive":"būti",
            "present":"yra",
            "past":"buvo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "būdavau",
            "būdavai",
            "būdavo",
            "būdavome",
            "būdavote",
            "būdavo"
         ]
      },
      {
         "verb":{
            "infinitive":"būti",
            "present":"yra",
            "past":"buvo"
         },
         "tense":"Future",
         "forms":[
            "būsiu",
            "būsi",
            "bus",
            "būsime",
            "būsite",
            "bus"
         ]
      },
      {
         "verb":{
            "infinitive":"būti",
            "present":"yra",
            "past":"buvo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "būk",
            "tegu būna",
            "būkime",
            "būkite",
            "tegu būna"
         ]
      },
      {
         "verb":{
            "infinitive":"būti",
            "present":"yra",
            "past":"buvo"
         },
         "tense":"Conditional",
         "forms":[
            "būčiau",
            "būtum",
            "būtų",
            "būtume / būtumėme",
            "būtute / būtumėte",
            "būtų"
         ]
      }
   ],
   "čiuožinėti":[
      {
         "verb":{
            "infinitive":"čiuožinėti",
            "present":"čiuožinėja",
            "past":"čiuožinėjo"
         },
         "tense":"Present",
         "forms":[
            "čiuožinėju",
            "čiuožinėji",
            "čiuožinėja",
            "čiuožinėjame",
            "čiuožinėjate",
            "čiuožinėja"
         ]
      },
      {
         "verb":{
            "infinitive":"čiuožinėti",
            "present":"čiuožinėja",
            "past":"čiuožinėjo"
         },
         "tense":"Past",
         "forms":[
            "čiuožinėjau",
            "čiuožinėjai",
            "čiuožinėjo",
            "čiuožinėjome",
            "čiuožinėjote",
            "čiuožinėjo"
         ]
      },
      {
         "verb":{
            "infinitive":"čiuožinėti",
            "present":"čiuožinėja",
            "past":"čiuožinėjo"
         },
         "tense":"PastContiniuos",
         "forms":[
            "čiuožinėdavau",
            "čiuožinėdavai",
            "čiuožinėdavo",
            "čiuožinėdavome",
            "čiuožinėdavote",
            "čiuožinėdavo"
         ]
      },
      {
         "verb":{
            "infinitive":"čiuožinėti",
            "present":"čiuožinėja",
            "past":"čiuožinėjo"
         },
         "tense":"Future",
         "forms":[
            "čiuožinėsiu",
            "čiuožinėsi",
            "čiuožinės",
            "čiuožinėsime",
            "čiuožinėsite",
            "čiuožinės"
         ]
      },
      {
         "verb":{
            "infinitive":"čiuožinėti",
            "present":"čiuožinėja",
            "past":"čiuožinėjo"
         },
         "tense":"Imperative",
         "forms":[
            "–",
            "čiuožinėk",
            "tegu čiuožinėja",
            "čiuožinėkime",
            "čiuožinėkite",
            "tegu čiuožinėja"
         ]
      },
      {
         "verb":{
            "infinitive":"čiuožinėti",
            "present":"čiuožinėja",
            "past":"čiuožinėjo"
         },
         "tense":"Conditional",
         "forms":[
            "čiuožinėčiau",
            "čiuožinėtum",
            "čiuožinėtų",
            "čiuožinėtume / čiuožinėtumėme",
            "čiuožinėtute / čiuožinėtumėte",
            "čiuožinėtų"
         ]
      }
   ]
}
"""
