source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:Max-Lumiere/Specs.git'

use_frameworks!
platform :ios, '15.0'

def available_pods
  use_frameworks!

  pod 'shared', :path => '../shared'
  pod 'LumiereToolkit', :git => 'git@github.com:Max-Lumiere/LumiereToolkit.git'
end

target 'iosApp' do
  available_pods
end

target 'iosAppTests' do
  available_pods

  pod 'Quick'
  pod 'Nimble'
  pod "Cuckoo"
end
