source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:Max-Lumiere/Specs.git'

ios_version = '15.0'
platform :ios, ios_version

def available_pods

  pod 'LumiereToolkit', :git => 'git@github.com:Max-Lumiere/LumiereToolkit.git'
end

target 'iosApp' do
  available_pods

  pod 'shared', :path => '../shared'
end

target 'iosAppTests' do
  available_pods

  pod 'Quick'
  pod 'Nimble'
end

post_install do |installer|

  installer.pods_project.build_configurations.each do |config|
    config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['PRODUCT_NAME'] == 'Quick' || config.build_settings['PRODUCT_NAME'] == 'Nimble'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = ios_version
      end
    end
  end
end

post_integrate do |installer|
  main_project = installer.aggregate_targets[0].user_project
  pods_project = installer.pods_project
  targets = main_project.targets + pods_project.targets
  targets.each do |target|
    run_script_build_phases = target.build_phases.filter { |phase| phase.is_a?(Xcodeproj::Project::Object::PBXShellScriptBuildPhase) }
    cocoapods_run_script_build_phases = run_script_build_phases.filter { |phase| phase.name.start_with?("[CP") }
    cocoapods_run_script_build_phases.each do |run_script|
      next unless (run_script.input_paths || []).empty? && (run_script.output_paths || []).empty?
      run_script.always_out_of_date = "1"
    end
  end
  main_project.save
  pods_project.save
end
